#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-ricky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-ricky
  template:
    metadata:
      labels:
        app: prod-stedi-ricky
    spec:
      containers:
        - name: prod-stedi-ricky
          image: gcr.io/cubs-consulting/stedi #THIS IMAGE NEEDS TO REFER TO THE NEW ARTIFACT REGISTRY / SAME IMAGE AS IN DEV-MANIFEST (LINE 34), PLACE IT HERE
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-ricky
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-ricky"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-ricky-nodeport
spec:
  selector:
    app: prod-stedi-ricky
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-ricky-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-ricky-public #THIS IP HAS NOT BEEN CREATED YET - NEED TO CREATE FIRST
    networking.gke.io/managed-certificates: prod-stedi-ricky-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-ricky-nodeport #THIS NEEDS TO MATCH LINE 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-ricky-certificate #THIS NEEDS TO MATCH LINE 68
spec:
  domains:
    - ricky.cit262.com #THIS IS A DNS RECORD THAT HAS NOT BEEN CREATED YET - WE NEED TO CREATE THAT FIRST
    
